print("jangan nora")
print("selamat siang")
print("jangan nangis")
print("selamat malam")
print("selamat sore")
print("selamat datang")
print("haram mencuri")
print("datang sebagai pemula")
print("pulang sebagai legenda")
print("hargai kawan mu")